# Project: test_second
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o CMyString.o $(RES)
LINKOBJ  = main.o CMyString.o $(RES)
LIBS =  -L"D:/software/Dev-Cpp/lib"  
INCS =  -I"D:/software/Dev-Cpp/include" 
CXXINCS =  -I"D:/software/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"D:/software/Dev-Cpp/include/c++/3.4.2/backward"  -I"D:/software/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"D:/software/Dev-Cpp/include/c++/3.4.2"  -I"D:/software/Dev-Cpp/include" 
BIN  = test_second.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before test_second.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "test_second.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

CMyString.o: CMyString.cpp
	$(CPP) -c CMyString.cpp -o CMyString.o $(CXXFLAGS)
